# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: minkky
google_analytics: Minji Seo
title: Minji Seo

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      all_title: minkky 의 끄적끄적
      title: POST
      url : "https://minkky.github.io"
      baseurl : ""

description: Stylish Jekyll Theme
author:
  name: Minji Seo
  email: minkky@sookmyung.ac.kr
  github: minkky
  linkedin: minkky
  bio: <b>Research field</b><br>Graph Similarity(embedding) with DL
  minion_image: //user-images.githubusercontent.com/16285746/62137824-91a03880-b321-11e9-822f-bc10ec6a67e8.jpg
  email_md5: 62137824-91a03880-b321-11e9-822f-bc10ec6a67e8.jpg

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
